fn main() {
    // impl From<bool> for i32
    let i1: i32 = false.into();
    let i2: i32 = i32::from(false);
    assert_eq!(i1, i2);
    assert_eq!(i1, 0);

    // FIX the error in two ways
    // 1. Use a similar type which impl From<char>
    let i3: i32 = 'a' as i32; // `char` to `i32` using its ASCII value

    // 2. Use a keyword from the last chapter
    let s: String = 'a'.to_string(); // Convert char to String

    println!("Success!");
}
#[derive(Debug)]
struct Number {
    value: i32,
}

impl From<i32> for Number {
    // IMPLEMENT `from` method
    fn from(value: i32) -> Self {
        Number { value }
    }
}

// FILL in the blanks
fn main() {
    let num = Number::from(30); // Using From to convert from i32 to Number
    assert_eq!(num.value, 30);

    let num: Number = 30.into(); // Using Into (which automatically calls From)
    assert_eq!(num.value, 30);

    println!("Success!");
}
use std::fs;
use std::io;
use std::num;

enum CliError {
    IoError(io::Error),
    ParseError(num::ParseIntError),
}

impl From<io::Error> for CliError {
    // IMPLEMENT from method
    fn from(error: io::Error) -> CliError {
        CliError::IoError(error)
    }
}

impl From<num::ParseIntError> for CliError {
    // IMPLEMENT from method
    fn from(error: num::ParseIntError) -> CliError {
        CliError::ParseError(error)
    }
}

fn open_and_parse_file(file_name: &str) -> Result<i32, CliError> {
    // ? automatically converts io::Error to CliError
    let contents = fs::read_to_string(&file_name)?; // io::Error -> CliError
    // num::ParseIntError -> CliError
    let num: i32 = contents.trim().parse()?; // ParseIntError -> CliError
    Ok(num)
}

fn main() {
    println!("Success!");
}
use std::convert::TryInto;

fn main() {
    let n: i16 = 256;

    // Into trait has a method `into`,
    // hence TryInto has a method ?
    let n: u8 = match n.try_into() { // Use `try_into` for a fallible conversion
        Ok(n) => n,
        Err(e) => {
            println!("there is an error when converting: {:?}, but we catch it", e.to_string());
            0
        }
    };

    assert_eq!(n, 0); // The conversion from 256 to u8 should fail and return 0.

    println!("Success!");
}
#[derive(Debug, PartialEq)]
struct EvenNum(i32);

impl TryFrom<i32> for EvenNum {
    type Error = ();

    // IMPLEMENT `try_from`
    fn try_from(value: i32) -> Result<Self, Self::Error> {
        if value % 2 == 0 {
            Ok(EvenNum(value))
        } else {
            Err(())
        }
    }
}

fn main() {
    assert_eq!(EvenNum::try_from(8), Ok(EvenNum(8)));
    assert_eq!(EvenNum::try_from(5), Err(()));

    // FILL in the blanks
    let result: Result<EvenNum, ()> = 8i32.try_into(); // Convert 8 into EvenNum
    assert_eq!(result, Ok(EvenNum(8)));
    let result: Result<EvenNum, ()> = 5i32.try_into(); // Convert 5 into EvenNum (will fail)
    assert_eq!(result, Err(()));

    println!("Success!");
}
